version: 2.1

jobs:
  sleep:
    parameters:
      duration:
        default: "45m"
        type: string
    docker:
      - image: cimg/go:1.23
    resource_class: small
    steps:
      - checkout
      - run: go run ./cmd/nothing-to-do <<parameters.duration>>
  fail:
    docker:
      - image: cimg/go:1.23
    steps:
      - run: exit 1

workflows:
  check:
    jobs:
      - fail
      - sleep:
          name: "sleep 1"
          duration: 1s
